A jornada de um desenvolvedor júnior - Lucas Sartori
Dev-ES/devesconf-2018-c4p pull request #1
Opened 2018-10-08 19:17 UTC by fang0rnz

2018-10-08 19:22 UTC, UsefulHunter commented
Só vejo vantagens em ver algo assim, seria um guia, ou talvez até uma forma de ser apresentado, para nós que estamos começando, o caminho das pedras a ser seguido.

2018-10-08 19:27 UTC, fang0rnz commented
valeu @UsefulHunter, o objetivo é exatamente de apresentar os problemas e desafios que passei e ajudar tanto gente muito mais experiente a facilitar esse aprendizado (gente que tá há muito tempo no mercado acaba esquecendo das dificuldades de quem está começando) quanto gente que tá entrando no mercado e tá aí cheio de dúvidas.

2018-10-08 19:39 UTC, gabrielreisn commented
Acho um tema incrível de palestra, engaja pessoas, o que é a na minha opinião a ideia maior de toda comunidade de desenvolvedores. Conhecendo bem a história do Lucas e tendo trabalhado com ele por um tempo vai ser algo muito proveitoso pra quem está começando na carreira :)

2018-10-08 19:48 UTC, lucianopf requested changes
Ta massa, só precisa consertar essas quebras de linhas malucas 😬

2018-10-08 19:48 UTC, lucianopf commented on lucas_sartori.md
> +adentrando nesse universo caótico.
consertar quebra de linha

2018-10-08 19:48 UTC, lucianopf commented on lucas_sartori.md
> +acelerado e impiedoso do mercado?
consertar quebra de linha

2018-10-08 19:48 UTC, lucianopf commented on lucas_sartori.md
> +mais de um ano de experiência profissional.
consertar quebra de linha

2018-10-09 13:41 UTC, jvrmaia commented
@fang0rnz maneiro, fiz um template de PR com as informações, pode colocar no formato?

https://github.com/Dev-ES/devesconf-2018-c4p/blob/master/.github/pull_request_template.md

2018-10-09 16:32 UTC, fang0rnz commented
@jvrmaia feito

2018-10-09 17:13 UTC, lucianopf approved these changes

2018-10-09 19:29 UTC, merged