add apply palestra microserviços
Dev-ES/devesconf-2018-c4p pull request #4
Opened 2018-10-10 22:03 UTC by brupinto

# Nome do palestrante
Microservices são mesmo microservices?

# Descreva o motivo do seu interesse de palestrar no evento
Compartilhar com a comunidade a experiências "amargas" no desenvolvimento de soluções com arquitetura de microservices.

2018-10-10 22:24 UTC, josmardias requested changes
@brupinto 
O seu documento está com o nome correto e na pasta correta.

Porém o conteúdo do arquivo não está no formato correto.
Você seguiu a estrutura de tópicos mas deixou de lado a formatação.
As marcações de tópico (no caso as #s) fazem toda diferença na visualização.

![image](https://user-images.githubusercontent.com/413430/46769350-e2c33b00-ccc1-11e8-847a-ce0e2c801887.png)

2018-10-11 04:06 UTC, brupinto commented
Ajustado conforme solicitado.

2018-10-11 14:11 UTC, josmardias approved these changes

2018-10-11 14:11 UTC, josmardias approved these changes
Obrigado @brupinto !

2018-10-11 14:11 UTC, merged